version: '3.3'

services:
  db:
    image: postgres:15.2
    container_name: db
    ports:
      - "5431:5432"
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PSW}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    ports:
      - "62:80"

  fastapi:
    build: .
    container_name: fastapi
    volumes:
      - app:/usr/src/app/migrations/versions
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    environment:
      - REDIS_PORT=6379
    ports:
      - "6600:6379"



volumes:
  pgdata:
  app: